[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "AGENTS.md",
]

[project]
name = "vscmnet2"
version = "1.0.8"
description = "CMNET2 functions for VapourSynth"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [{name = "Dan64", email = "whitedan64@gmail.com"}]
keywords = ["CMNET2", "VapourSynth", "Colorization"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Multimedia :: Video"
]
dependencies = [   
  "numpy>=1.26.2",
  "torch>=2.7.0",
  "torchvision>=0.22",
  "pillow>=9.0.0",
  "opencv-python>=4.0.0",
  "scikit-image>=0.20.0",
  "einops>=0.8",
  "safetensors>=0.4.0",
]

[project.urls]
"Homepage" = "https://github.com/dan64/vs-cmnet2"
"Bug Tracker" = "https://github.com/dan64/vs-cmnet2/issues"
